#deptracimports:
#    - deptrac.baseline.yaml
parameters:
    paths:
        - ./src
    exclude_files:
        - '#.*test.*#'
    layers:
        -   name: ControllersCommands
            collectors:
                -   type: className
                    regex: App\\(Controller|Command)\\(SecurityController|UserController|AddUserCommand|DeleteUserCommand|ListUsersCommand)
        -   name: Persistence
            collectors:
                -   type: className
                    regex: App\\(Entity|Repository)\\(User|UserRepository)
        -   name: Service
            collectors:
                -   type: className
                    regex: App\\(Form)\\(ChangePasswordType|UserType)
        -   name: Shared
            collectors:
                -   type: className
                    regex: App\\Utils.*
        -   name: System
            collectors:
                -   type: bool
                    must:
                        - type: className
                          regex: App\\.*
                    must_not:
                        - type: layer
                          layer: ControllersCommands
                        - type: layer
                          layer: Persistence
                        - type: layer
                          layer: Service
                        - type: layer
                          layer: Shared
                        - type: className
                          regex: App\\DataFixtures\\.*
    ruleset:
        ControllersCommands:
            - Persistence
            - Service
            - Shared
        Service:
            - Persistence
        Persistence:
        Shared:
        System:
    formatters:
        graphviz:
            hidden_layers:  []
            groups:
                SecurityModule:
                    - ControllersCommands
                    - Persistence
                    - Service
            point_to_groups: false